name: Run E2E tests
on: push
jobs:
  e2e:
    name: Run E2E test
    runs-on: ubuntu-latest
    steps:
      - name: Check out test private repo
        uses: actions/checkout@v3
        with:
          repository: vector-im/static-call-participant
          ref: refs/heads/main
          path: static-call-participant
          token: ${{ secrets.CHECKOUT_PRIVATE_REPO }}
      - name: Build Image
        run: "cd static-call-participant && docker build --no-cache --tag matrixdotorg/chrome-node-static-call-participant:latest ."
      - name: Run E2E tests
        run: "docker run --rm -v '${{ github.workspace }}/static-call-participant/callemshost-users.txt:/opt/app/callemshost-users.txt' matrixdotorg/chrome-node-static-call-participant:latest ./e2e.sh"
