name: Run E2E test
on: push
jobs:
  e2e:
    name: Run E2E tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out test private repo
        uses: actions/checkout@v3
        with:
          repository: vector-im/static-call-participant
          ref: refs/heads/e2e
          path: static-call-participant
          token: ${{ secrets.CHECKOUT_PRIVATE_REPO }}
      - name: Run E2E test
        run: "docker run --user root --rm -v '${{ github.workspace }}/static-call-participant:/opt/' node:18 ./opt/e2e.sh"
